version: 2.1
# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  ruby: circleci/ruby@2.1.3
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  test:
    parallelism: 2
    resource_class: arm.medium
    docker:
      - image: cimg/ruby:3.2.2 # You might need `cimg/ruby:3.2.2-node` for JS install
      - image: arm64v8/postgres:16.1
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circleci_test
          POSTGRES_PASSWORD: ""
      # Use circleci/browser-tools instead
      #- image: browserless/chrome:1.59-chrome-stable
      #  environment:
      #    PORT: 3000
      #    CONNECTION_TIMEOUT: 600000
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      DATABASE_URL: "postgres://ubuntu@localhost:5432/circleci_test"
      RAILS_ENV: test
      CI: true
      CHROME_URL: http://localhost:3000
    steps:
      - checkout
#      - browser-tools/install-chrome
      - run:
        command: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
          echo "Installing Chrome for ARM64"
          sh -c 'echo "deb [arch=arm64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y google-chrome-stable
          echo "test/verify installation"
          google-chrome-stable --version | grep "stable" >/dev/null 2>&1;
        name: Install chrome
      - ruby/install-deps
      - run:
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
          name: Wait for DB
      - run:
          command: dockerize -wait http://localhost:3000 -timeout 1m
          name: Wait for Chrome
      - run:
          command: bundle exec rails db:schema:load --trace
          name: Database setup
      - run:
          command: |
            circleci tests glob "test/**/*_test.rb" | circleci tests run --command="xargs bundle exec rake test:all" --verbose --split-by=timings
          name: Run all tests
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: test/reports/screenshots
          destination: screenshots

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_and_test:
    jobs:
      - test